version: "3.7"

services:
  db:
    image: postgres:15-alpine
    container_name: hapi-fhir-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - hapi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    restart: unless-stopped
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db

volumes:
  hapi_postgres_data:
    driver: local

configs:
  hapi:
    file: ./hapi.application.yaml

