spring:
  datasource:
    url: jdbc:postgresql://db:5432/hapi
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false

hapi:
  fhir:
    version: R4
    default_encoding: json
    default_pretty_print: true
    server_address: 'http://localhost:8080/fhir'
    ig_runtime_upload_enabled: true

  # Enable auditing for HIPAA compliance
  audit:
    enabled: true

  # Enable subscriptions (for future real-time features)
  subscription:
    resthook_enabled: true
    websocket_enabled: true

# Uncomment and adjust for production security
# server:
#   port: 8080
#   ssl:
#     enabled: true
#     key-store: /path/to/keystore.p12
#     key-store-password: password
#     key-store-type: PKCS12

